name: Build and deploy image to development cluster

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: vincentramaputra/viscord-web
          tags: |
            type=sha
      - name: Build and push the image
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{steps.meta.outputs.labels}}
    outputs:
      image_tag: ${{ steps.meta.outputs.version }}

  update-infra:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v4
        with:
          repository: Laevateinn17/viscord-infra
          token: ${{ secrets.INFRA_REPO_TOKEN }}
          path: infra
      - name: Install kustomize
        run: |
          curl -s https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh | bash
          sudo mv kustomize /usr/local/bin/
      - name: Update image tag
        run: |
          cd infra/k8s/apps/web-client/overlays/dev
          IMAGE_TAG=${{ needs.build.outputs.image_tag }}
          kustomize edit set image vincentramaputra/viscord-web:$IMAGE_TAG
      - name: Commit and push to infra repo
        run: |
          IMAGE_TAG=${{ needs.build.outputs.image_tag }}
          cd infra
          git config user.name "ci-bot"
          git config user.email "ci@bot"
          git add .
          git commit -m "update: updated web-client image tag to $IMAGE_TAG"
          git push

  deploy-azure:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Update Azure Web App container image
        run: |
          IMAGE_TAG=${{ needs.build.outputs.image_tag }}
          az webapp config container set \
            --name viscord \
            --resource-group my-resourcegroup \
            --container-image-name vincentramaputra/viscord-web:$IMAGE_TAG \
            --container-registry-url https://index.docker.io

      - name: Restart Azure Web App
        run: az webapp restart --name viscord --resource-group my-resourcegroup
